name: neonday_http_ex
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  true_core:
    git:
      url: https://github.com/TrueCollaboration/true_core.dart.git
  json_ex:
    git:
      url: https://github.com/TrueCollaboration/json_ex.dart.git
  neonday_network_ex:
    git:
      url: https://github.com/PrettyTeen/neonday_network_ex.git



dev_dependencies:
  flutter_test:
    sdk: flutter
